# Generated by Django 5.2.13 on 2026-04-19 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='game_sessions.team')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='game_sessions.turn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='accounts.profile')),
            ],
            options={
                'db_table': 'decisions',
                'unique_together': {('turn', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TurnResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpis', models.JSONField(default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game_sessions.team')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game_sessions.turn')),
            ],
            options={
                'db_table': 'turn_results',
                'unique_together': {('turn', 'team')},
            },
        ),
    ]
