# Generated by Django 5.2.13 on 2026-04-19 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('enterprise', 'Entreprise')], default='free', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('max_formateurs', models.IntegerField(default=1)),
                ('max_scenarios', models.IntegerField(default=3)),
                ('max_sessions', models.IntegerField(default=5)),
                ('ai_generation_enabled', models.BooleanField(default=False)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
    ]
