# Generated by Django 5.2.13 on 2026-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organisme', 'Organisme'), ('formateur', 'Formateur'), ('joueur', 'Joueur')], default='joueur', max_length=20),
        ),
    ]
